### ISSUE TITLE
Server Not Loading on Newest Version

### ISSUE THREAD

**Issue by kleemat** [mathewthe2/AnkiDojo#11]
The server page isn't loading for me on Anki 23.10.1 with the newest version of AnkiDojo. It does redirect from `http://localhost:5008/` to `http://localhost:5008/apps.html`, so I think it's running, but it returns a 404. I'm seeing the problem on both Windows 10 and Ubuntu 22.

Let me know if there's any diagnostic info I can collect for you.

**Comment by mathewthe2** [comment]
Thanks for the heads up. There was a build issue. I've updated the patch and it should work now.
