### ISSUE TITLE
Crash on large number of cards in bulk add

### ISSUE THREAD

**Issue by mathewthe2** [mathewthe2/AnkiDojo#3]
Issue: Crashing when adding large number of cards with audio included.
Possible solution: processes downloading audio files in parallel (in ankiconnect.py)

**Comment by postkevone** [comment]
I don't know if this is related, but I get this error when I try to use Passage in Card Builder:
```
Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'map')
at card-builder-4b7d228926b94485.js:1:11323
```

**Comment by mathewthe2** [comment]
What is your passage?

Have you installed the [Mecab Unidic Addon](https://github.com/ianki/MecabUnidic/releases/download/v3.1.0/MecabUnidic3.1.0.ankiaddon)?

**Comment by postkevone** [comment]
This is my passage file: [L4.txt](https://github.com/mathewthe2/AnkiDojo/files/9664982/L4.txt)

Anyway I installed the mecab addon and now it works, thanks.
