### ISSUE TITLE
Anki Crashes when Bulk Adding Cards (macOS)

### ISSUE THREAD

**Issue by 70fu** [mathewthe2/AnkiDojo#5]
Anki crashes, whenever I try to bulk add cards, the cards are not added to the deck. The amount of cards trying to add does not matter, I tried with 1-10 cards.
I am using macOS with Anki 2.1.63, but I think the bug appeared since Anki 2.1.62.

The macOS crash log is attached, let me know how I can help pinpointing the problem  :)
[anki-crash-log.txt](https://github.com/mathewthe2/AnkiDojo/files/11493624/anki-crash-log.txt)

**Comment by 70fu** [comment]
I can confirm, that the issue is eliminated by downgrading to Anki 2.1.61.

**Comment by mathewthe2** [comment]
I can identify the lines causing the problem:
https://github.com/mathewthe2/AnkiDojo/blob/8f3778ec86b487f09ba43edb5ea17c750fe67a4e/server/anki_connect.py#L18
https://github.com/mathewthe2/AnkiDojo/blob/8f3778ec86b487f09ba43edb5ea17c750fe67a4e/server/anki_connect.py#L23

They are directly referenced from the [AnkiConnect codebase](https://github.com/FooSoft/anki-connect/blob/master/plugin/__init__.py) and AnkiConnect still seems to work fine with these lines. I cannot figure out what changed with Anki that is making this addon crash.

**Comment by 70fu** [comment]
Sorry for the late reply, the referenced commit fixed the issue, but it seems it introduced a new one. Now the cards are always added to the Default deck.

**Comment by mathewthe2** [comment]
Sorry, I was experimenting and forgot to clean up my commit. Should add to the correct deck now.
