### ISSUE TITLE
Word audio is not added

### ISSUE THREAD

**Issue by ale-meacci** [mathewthe2/AnkiDojo#7]
When I add new cards I get "You must provide a "data", "path", or "url" field." in the word audio field. I have no idea how to fix this. I'm using anki 2.1.65 Qt6.

**Comment by mathewthe2** [comment]
I just tested on 2.1.65 Mac Apple Silicon and had no apparent issues with adding word audio.

On the card preview page, can you hear the word audio when you right click on the audio icon on the far left?

<img width="1408" alt="Screenshot 2023-08-10 at 8 45 30" src="https://github.com/mathewthe2/AnkiDojo/assets/13146030/f3affb59-a978-4c67-8846-6fc4facab539">

**Comment by ale-meacci** [comment]
Sorry for the late reply, this is what happens to me, I can't really see the audio button, is it because I'm on windows?

![Screenshot (3)](https://github.com/mathewthe2/AnkiDojo/assets/55414793/94547492-1003-48cc-b356-556de05367eb)

**Comment by mathewthe2** [comment]
You have to enable word audio by clicking on the settings icon. It is turned off by default.
